import {
  faCodepen,
  faGithub,
  faLinkedin,
  faXTwitter,
  faGitlab,
  faStackOverflow,
  faMedium,
  faDribbble,
  faInstagram,
  faYoutube,
  faDev,
  faBehance,
  faBluesky,
  IconDefinition,
} from '@fortawesome/free-brands-svg-icons';
import {
  faGlobe,
  faLink,
  faEnvelope,
  faPhone,
  faLocationDot,
  faFileArrowDown,
  faXmark,
  faChevronUp,
  faChevronDown,
  faPlus,
  faBriefcase,
  faTrashCan,
  faPen,
} from '@fortawesome/free-solid-svg-icons';

export const Icon = {
  faLinkedin,
  faGlobe,
  faGithub,
  faCodepen,
  faXTwitter,
  faGitlab,
  faStackOverflow,
  faMedium,
  faDribbble,
  faInstagram,
  faYoutube,
  faDev,
  faBehance,
  faBluesky,
  faLink,
  faLocationDot,
  faEnvelope,
  faPhone,
  faFileArrowDown,
  faXmark,
  faChevronUp,
  faChevronDown,
  faPlus,
  faBriefcase,
  faTrashCan,
  faPen,
} as const satisfies Record<string, IconDefinition>;

/** Icons offered in the link icon picker (brand/social + generic). */
export const LINK_ICONS: IconDefinition[] = [
  faLink,
  faGlobe,
  faEnvelope,
  faLinkedin,
  faGithub,
  faGitlab,
  faXTwitter,
  faStackOverflow,
  faMedium,
  faDev,
  faDribbble,
  faBehance,
  faInstagram,
  faYoutube,
  faBluesky,
  faCodepen,
];
